"""Lazy public exports.

Independent Harness modules load without the optional Host integration. Historical
exports resolve on first access and preserve the pre-1.0 compatibility surface.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_HOST_EXTRA_MESSAGE = ("Ordivon Harness Host integration is not installed; "
    "install ordivon-harness[host] for Host-backed APIs")

_EXPORTS: dict[str, tuple[str, str]] = {
    'COMPLETION_DECIDED': ('.event_kinds', 'COMPLETION_DECIDED'),
    'COMPLETION_PROPOSED': ('.event_kinds', 'COMPLETION_PROPOSED'),
    'HARNESS_ASSIGNMENT_COMMITTED': ('.event_kinds', 'HARNESS_ASSIGNMENT_COMMITTED'),
    'HARNESS_EVENT_KINDS': ('.event_kinds', 'HARNESS_EVENT_KINDS'),
    'HARNESS_PROVIDER_CALL_CLAIMED': ('.event_kinds', 'HARNESS_PROVIDER_CALL_CLAIMED'),
    'HARNESS_PROVIDER_CALL_COMPLETED': ('.event_kinds', 'HARNESS_PROVIDER_CALL_COMPLETED'),
    'HARNESS_PROVIDER_CALL_DISPATCHING': ('.event_kinds', 'HARNESS_PROVIDER_CALL_DISPATCHING'),
    'HARNESS_PROVIDER_CALL_FAILED': ('.event_kinds', 'HARNESS_PROVIDER_CALL_FAILED'),
    'HARNESS_PROVIDER_CALL_SUPERSEDED': ('.event_kinds', 'HARNESS_PROVIDER_CALL_SUPERSEDED'),
    'HARNESS_PROVIDER_CALL_UNKNOWN': ('.event_kinds', 'HARNESS_PROVIDER_CALL_UNKNOWN'),
    'HARNESS_RUN_ABANDONED': ('.event_kinds', 'HARNESS_RUN_ABANDONED'),
    'HARNESS_RUN_RECORDED': ('.event_kinds', 'HARNESS_RUN_RECORDED'),
    'HARNESS_RUN_RECOVERY_RECORDED': ('.event_kinds', 'HARNESS_RUN_RECOVERY_RECORDED'),
    'HARNESS_RUN_SNAPSHOT_RECORDED': ('.event_kinds', 'HARNESS_RUN_SNAPSHOT_RECORDED'),
    'HARNESS_TOOL_STEP_PREPARED': ('.event_kinds', 'HARNESS_TOOL_STEP_PREPARED'),
    'HARNESS_TOOL_STEP_RECORDED': ('.event_kinds', 'HARNESS_TOOL_STEP_RECORDED'),
    'CodexAppNormalizedEvent': ('.codex_app', 'CodexAppNormalizedEvent'),
    'CodexAppServerDriver': ('.codex_app', 'CodexAppServerDriver'),
    'CodexAppServerError': ('.codex_app', 'CodexAppServerError'),
    'CodexAppServerExited': ('.codex_app', 'CodexAppServerExited'),
    'CodexAppServerProtocolError': ('.codex_app', 'CodexAppServerProtocolError'),
    'CodexAppServerTimeout': ('.codex_app', 'CodexAppServerTimeout'),
    'CodexAppThread': ('.codex_app', 'CodexAppThread'),
    'CodexAppTurnHandle': ('.codex_app', 'CodexAppTurnHandle'),
    'CodexAppTurnResult': ('.codex_app', 'CodexAppTurnResult'),
    'CommittedHarnessAssignment': ('.host', 'CommittedHarnessAssignment'),
    'CompletionDecision': ('.models', 'CompletionDecision'),
    'CompletionDecisionReceipt': ('.models', 'CompletionDecisionReceipt'),
    'CompletionMode': ('.runner', 'CompletionMode'),
    'DomainToolBridge': ('.domain_tools', 'DomainToolBridge'),
    'DomainToolCatalog': ('.domain_tools', 'DomainToolCatalog'),
    'DomainToolLoopPlan': ('.domain_tools', 'DomainToolLoopPlan'),
    'DomainToolLoopRunner': ('.domain_tools', 'DomainToolLoopRunner'),
    'CompletionProposal': ('.models', 'CompletionProposal'),
    'CompletionRoute': ('.disposition', 'CompletionRoute'),
    'CompletionVerification': ('.contracts', 'CompletionVerification'),
    'GrantedExecutionCheck': ('.contracts', 'GrantedExecutionCheck'),
    'HARNESS_STORE_EVENT_KINDS': ('.store', 'HARNESS_STORE_EVENT_KINDS'),
    'HarnessArtifactReference': ('.agent_tool_observation', 'HarnessArtifactReference'),
    'HarnessBoundReference': ('.core_contracts', 'HarnessBoundReference'),
    'ExternalHarnessRequestInventoryItem': ('.cutover', 'ExternalHarnessRequestInventoryItem'),
    'HarnessCutoverInventory': ('.cutover', 'HarnessCutoverInventory'),
    'HarnessCutoverReceipt': ('.cutover', 'HarnessCutoverReceipt'),
    'HarnessCutoverStatus': ('.cutover', 'HarnessCutoverStatus'),
    'HarnessStoreMode': ('.cutover', 'HarnessStoreMode'),
    'IndependentHarnessRunInventoryItem': ('.cutover', 'IndependentHarnessRunInventoryItem'),
    'LegacyHarnessRunInventoryItem': ('.cutover', 'LegacyHarnessRunInventoryItem'),
    'activate_cutover': ('.cutover', 'activate_cutover'),
    'assert_legacy_writer_allowed': ('.cutover', 'assert_legacy_writer_allowed'),
    'build_cutover_inventory': ('.cutover', 'build_cutover_inventory'),
    'cutover_status': ('.cutover', 'cutover_status'),
    'rollback_cutover': ('.cutover', 'rollback_cutover'),
    'HarnessCorrelationContext': ('.core_contracts', 'HarnessCorrelationContext'),
    'HarnessDispatchFenceV2': ('.ordivon.continuity_records', 'HarnessDispatchFenceV2'),
    'HarnessEventAdmission': ('.store', 'HarnessEventAdmission'),
    'HarnessEventWrite': ('.store', 'HarnessEventWrite'),
    'HarnessExecutionBinding': ('.execution_binding', 'HarnessExecutionBinding'),
    'HarnessEventConflict': ('.sqlite_store', 'HarnessEventConflict'),
    'HarnessJournalCorruption': ('.sqlite_store', 'HarnessJournalCorruption'),
    'HarnessLeaseConflict': ('.sqlite_store', 'HarnessLeaseConflict'),
    'HarnessLeaseHeld': ('.sqlite_store', 'HarnessLeaseHeld'),
    'HarnessObjectCorrupt': ('.sqlite_store', 'HarnessObjectCorrupt'),
    'HarnessObjectMissing': ('.sqlite_store', 'HarnessObjectMissing'),
    'HarnessPrivacyPolicy': ('.core_contracts', 'HarnessPrivacyPolicy'),
    'HarnessRevisionConflict': ('.sqlite_store', 'HarnessRevisionConflict'),
    'HarnessRunContinuityStore': ('.ordivon.run_store_port', 'HarnessRunContinuityStore'),
    'HarnessRunContract': ('.core_contracts', 'HarnessRunContract'),
    'HarnessRunStoreBinding': ('.ordivon.run_store_port', 'HarnessRunStoreBinding'),
    'HarnessRunEventRecord': ('.store', 'HarnessRunEventRecord'),
    'HarnessRunLease': ('.store', 'HarnessRunLease'),
    'HarnessRunProjection': ('.store', 'HarnessRunProjection'),
    'HarnessRunStatus': ('.store', 'HarnessRunStatus'),
    'HarnessRuntimeClient': ('.runtime_port', 'HarnessRuntimeClient'),
    'HarnessRuntimeClientError': ('.runtime_port', 'HarnessRuntimeClientError'),
    'HarnessRuntimeErrorDetail': ('.runtime_port', 'HarnessRuntimeErrorDetail'),
    'HarnessRuntimeReference': ('.execution_binding', 'HarnessRuntimeReference'),
    'HarnessRuntimeToolRejected': ('.runtime_port', 'HarnessRuntimeToolRejected'),
    'HarnessStore': ('.store', 'HarnessStore'),
    'HarnessStoreError': ('.sqlite_store', 'HarnessStoreError'),
    'HarnessTerminalConflict': ('.sqlite_store', 'HarnessTerminalConflict'),
    'HarnessToolObservation': ('.agent_tool_observation', 'HarnessToolObservation'),
    'INDEPENDENT_REPOSITORY_REPAIR_TOOL_DEFINITIONS': ('.ordivon.sqlite_repository_repair_bridge', 'INDEPENDENT_REPOSITORY_REPAIR_TOOL_DEFINITIONS'),
    'INDEPENDENT_REPOSITORY_REPAIR_TOOL_GRANT': ('.ordivon.sqlite_repository_repair_bridge', 'INDEPENDENT_REPOSITORY_REPAIR_TOOL_GRANT'),
    'INDEPENDENT_REPOSITORY_REPAIR_TOOL_GRANT_DIGEST': ('.ordivon.sqlite_repository_repair_bridge', 'INDEPENDENT_REPOSITORY_REPAIR_TOOL_GRANT_DIGEST'),
    'INDEPENDENT_REPOSITORY_REPAIR_TOOL_SURFACE': ('.ordivon.sqlite_repository_repair_bridge', 'INDEPENDENT_REPOSITORY_REPAIR_TOOL_SURFACE'),
    'INDEPENDENT_REPOSITORY_REPAIR_TOOL_SURFACE_DIGEST': ('.ordivon.sqlite_repository_repair_bridge', 'INDEPENDENT_REPOSITORY_REPAIR_TOOL_SURFACE_DIGEST'),
    'SQLiteHarnessRepositoryRepairRuntimeBridge': ('.ordivon.sqlite_repository_repair_bridge', 'SQLiteHarnessRepositoryRepairRuntimeBridge'),
    'INDEPENDENT_SEARCH_TOOL_GRANT': ('.ordivon.sqlite_runtime_bridge', 'INDEPENDENT_SEARCH_TOOL_GRANT'),
    'INDEPENDENT_SEARCH_TOOL_GRANT_DIGEST': ('.ordivon.sqlite_runtime_bridge', 'INDEPENDENT_SEARCH_TOOL_GRANT_DIGEST'),
    'INDEPENDENT_SEARCH_TOOL_SURFACE': ('.ordivon.sqlite_runtime_bridge', 'INDEPENDENT_SEARCH_TOOL_SURFACE'),
    'INDEPENDENT_SEARCH_TOOL_SURFACE_DIGEST': ('.ordivon.sqlite_runtime_bridge', 'INDEPENDENT_SEARCH_TOOL_SURFACE_DIGEST'),
    'NO_TOOL_AGENT_GRANT': ('.ordivon.sqlite_agent_bridge', 'NO_TOOL_AGENT_GRANT'),
    'NO_TOOL_AGENT_GRANT_DIGEST': ('.ordivon.sqlite_agent_bridge', 'NO_TOOL_AGENT_GRANT_DIGEST'),
    'NO_TOOL_AGENT_SURFACE': ('.ordivon.sqlite_agent_bridge', 'NO_TOOL_AGENT_SURFACE'),
    'NO_TOOL_AGENT_SURFACE_DIGEST': ('.ordivon.sqlite_agent_bridge', 'NO_TOOL_AGENT_SURFACE_DIGEST'),
    'SQLiteHarnessAgentBridge': ('.ordivon.sqlite_agent_bridge', 'SQLiteHarnessAgentBridge'),
    'SQLiteHarnessRunContinuityStore': ('.ordivon.sqlite_run_store', 'SQLiteHarnessRunContinuityStore'),
    'SQLiteHarnessRuntimeBridge': ('.ordivon.sqlite_runtime_bridge', 'SQLiteHarnessRuntimeBridge'),
    'SQLiteHarnessStore': ('.sqlite_store', 'SQLiteHarnessStore'),
    'StandaloneHarnessExecution': ('.standalone', 'StandaloneHarnessExecution'),
    'StandaloneHarnessRunner': ('.standalone', 'StandaloneHarnessRunner'),
    'StandaloneToolBridge': ('.standalone', 'StandaloneToolBridge'),
    'StoredIndependentRunResult': ('.independent_result', 'StoredIndependentRunResult'),
    'StoredHarnessObject': ('.store', 'StoredHarnessObject'),
    'backup_harness_store': ('.store_ops', 'backup_harness_store'),
    'restore_harness_backup': ('.store_ops', 'restore_harness_backup'),
    'verify_harness_backup': ('.store_ops', 'verify_harness_backup'),
    'HarnessAssignment': ('.models', 'HarnessAssignment'),
    'HarnessCancellationResult': ('.runner', 'HarnessCancellationResult'),
    'HarnessCapabilityManifest': ('.models', 'HarnessCapabilityManifest'),
    'HarnessExecutionResult': ('.runner', 'HarnessExecutionResult'),
    'HarnessHost': ('.host', 'HarnessHost'),
    'HarnessLifecycleError': ('.host', 'HarnessLifecycleError'),
    'HarnessProviderCallRecord': ('.protocol', 'HarnessProviderCallRecord'),
    'HarnessProviderCallRecordV2': ('.ordivon.continuity_records', 'HarnessProviderCallRecordV2'),
    'HarnessProviderCallClaimHeld': ('.ordivon.run_store_port', 'HarnessProviderCallClaimHeld'),
    'HarnessProviderCallFailureReceipt': ('.protocol', 'HarnessProviderCallFailureReceipt'),
    'HarnessProviderCallRecoveryRequired': ('.ordivon.run_store_port', 'HarnessProviderCallRecoveryRequired'),
    'HarnessProviderCallRequestMismatch': ('.ordivon.run_store_port', 'HarnessProviderCallRequestMismatch'),
    'HarnessProviderCallSource': ('.protocol', 'HarnessProviderCallSource'),
    'HarnessProviderCallStatus': ('.protocol', 'HarnessProviderCallStatus'),
    'HarnessRunPlan': ('.runner', 'HarnessRunPlan'),
    'HarnessRunReceipt': ('.models', 'HarnessRunReceipt'),
    'HarnessRunner': ('.runner', 'HarnessRunner'),
    'HarnessStatus': ('.runner', 'HarnessStatus'),
    'HarnessSuperseded': ('.host', 'HarnessSuperseded'),
    'HermesACPDriver': ('.hermes_acp', 'HermesACPDriver'),
    'HermesACPError': ('.hermes_acp', 'HermesACPError'),
    'HermesACPExited': ('.hermes_acp', 'HermesACPExited'),
    'HermesACPNormalizedEvent': ('.hermes_acp', 'HermesACPNormalizedEvent'),
    'HermesACPPromptHandle': ('.hermes_acp', 'HermesACPPromptHandle'),
    'HermesACPPromptResult': ('.hermes_acp', 'HermesACPPromptResult'),
    'HermesACPProtocolError': ('.hermes_acp', 'HermesACPProtocolError'),
    'HermesACPSession': ('.hermes_acp', 'HermesACPSession'),
    'HermesACPTimeout': ('.hermes_acp', 'HermesACPTimeout'),
    'HistoryValidation': ('.history', 'HistoryValidation'),
    'IndependentCompletionProposal': ('.independent_result', 'IndependentCompletionProposal'),
    'IndependentHarnessRunReceipt': ('.independent_result', 'IndependentHarnessRunReceipt'),
    'IndependentRunRecorder': ('.independent_result', 'IndependentRunRecorder'),
    'HarnessExternalContractResolver': ('.host_external_adapter', 'HarnessExternalContractResolver'),
    'HarnessExternalDriverFactory': ('.host_external_adapter', 'HarnessExternalDriverFactory'),
    'HarnessExternalRunDriver': ('.host_external_adapter', 'HarnessExternalRunDriver'),
    'HarnessExternalStatus': ('.host_external_adapter', 'HarnessExternalStatus'),
    'HostExternalRequestView': ('.host_external_adapter', 'HostExternalRequestView'),
    'OrdivonHarnessExternalCompletionProposal': ('.host_external_adapter', 'OrdivonHarnessExternalCompletionProposal'),
    'OrdivonHarnessExternalExecutorAdapter': ('.host_external_adapter', 'OrdivonHarnessExternalExecutorAdapter'),
    'OrdivonHarnessExternalObservation': ('.host_external_adapter', 'OrdivonHarnessExternalObservation'),
    'HostRuntimeReference': ('.runtime_refs', 'HostRuntimeReference'),
    'NativeHarnessRunContract': ('.contracts', 'NativeHarnessRunContract'),
    'NativeRunAbandonment': ('.recovery', 'NativeRunAbandonment'),
    'NativeRunDisposition': ('.disposition', 'NativeRunDisposition'),
    'NativeRunFacts': ('.disposition', 'NativeRunFacts'),
    'NativeRunOperatorAction': ('.disposition', 'NativeRunOperatorAction'),
    'NativeRunPhase': ('.disposition', 'NativeRunPhase'),
    'NativeRunRecoveryAssessment': ('.recovery', 'NativeRunRecoveryAssessment'),
    'NativeRunRecoveryController': ('.recovery_controller', 'NativeRunRecoveryController'),
    'NativeRunRecoveryResult': ('.recovery_controller', 'NativeRunRecoveryResult'),
    'NativeToolCatalogSnapshot': ('.tool_semantics', 'NativeToolCatalogSnapshot'),
    'NativeToolRecoveryConsequence': ('.tool_semantics', 'NativeToolRecoveryConsequence'),
    'NativeToolSpec': ('.tool_semantics', 'NativeToolSpec'),
    'OperatorHandoffCapsule': ('.handoff', 'OperatorHandoffCapsule'),
    'PreparedHarnessAttempt': ('.host', 'PreparedHarnessAttempt'),
    'ProposedCompletion': ('.host', 'ProposedCompletion'),
    'RecordedHarnessRun': ('.host', 'RecordedHarnessRun'),
    'RecordedNativeRunAbandonment': ('.host', 'RecordedNativeRunAbandonment'),
    'RecordedNativeRunRecovery': ('.host', 'RecordedNativeRunRecovery'),
    'ReplacementScope': ('.disposition', 'ReplacementScope'),
    'RunHandle': ('.runner', 'RunHandle'),
    'SEARCH_WORKSPACE_DEFINITION': ('.ordivon.sqlite_runtime_bridge', 'SEARCH_WORKSPACE_DEFINITION'),
    'TaskAttemptDescriptor': ('.models', 'TaskAttemptDescriptor'),
    'TaskContract': ('.contracts', 'TaskContract'),
    'ToolGrant': ('.contracts', 'ToolGrant'),
    'build_harness_workspace_exec_request': ('.runtime_refs', 'build_harness_workspace_exec_request'),
    'build_harness_workspace_exec_request_from_binding': ('.execution_binding', 'build_harness_workspace_exec_request_from_binding'),
    'derive_native_run_disposition': ('.disposition', 'derive_native_run_disposition'),
    'find_runtime_jobs_by_client_request': ('.runtime_port', 'find_runtime_jobs_by_client_request'),
    'harness_run_runtime_binding_digest': ('.runtime_refs', 'harness_run_runtime_binding_digest'),
    'harness_runtime_client_request_id': ('.runtime_refs', 'harness_runtime_client_request_id'),
    'host_runtime_references': ('.runtime_refs', 'host_runtime_references'),
    'legacy_grant_recovery_consequence': ('.tool_semantics', 'legacy_grant_recovery_consequence'),
    'operator_handoff': ('.handoff', 'operator_handoff'),
    'task_runtime_binding_digest': ('.runtime_refs', 'task_runtime_binding_digest'),
    'validate_history': ('.history', 'validate_history'),
}

__all__ = list(_EXPORTS)

def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute_name = target
    try:
        module = import_module(module_name, __name__)
    except ModuleNotFoundError as error:
        if error.name == "ordivon_host" or (error.name or "").startswith("ordivon_host."):
            raise ModuleNotFoundError(_HOST_EXTRA_MESSAGE) from error
        raise
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value

def __dir__() -> list[str]:
    # Root getattr remains a historical compatibility path, but capability
    # discovery should advertise the recommended Host-free facade rather than
    # optional Host-backed symbols that may fail on a base installation.
    api = import_module(".api", __name__)
    return sorted(set(globals()) | set(api.__all__) | {"api", "core", "host_api"})
