"""Host-independent Ordivon Harness public facade.

This module is the supported import surface for caller-neutral Run contracts,
independent Journal/CAS persistence, standalone execution and Runtime Tool
bridging. Importing it never requires ``ordivon-host``.
"""

from .agent_tool_observation import HarnessArtifactReference, HarnessToolObservation
from .completion import (
    decode_structured_completion_result,
    structured_completion_contract_digest,
    structured_completion_result_schema,
)
from .core_contracts import (
    HarnessBoundReference,
    HarnessCorrelationContext,
    HarnessPrivacyPolicy,
    HarnessRunContract,
    STRUCTURED_COMPLETION_MODE,
)
from .claim_standing import (
    OperationalClaimEvidenceRole,
    OperationalClaimRef,
    OperationalClaimStandingView,
    project_operational_claim_standing_view,
)
from .execution_binding import (
    HarnessExecutionBinding,
    HarnessRuntimeReference,
    build_harness_workspace_exec_request_from_binding,
)
from .mandate import (
    CompiledHarnessAttempt,
    HarnessExecutionMandate,
    HarnessMandateConsumption,
    HarnessExecutionProfile,
    HarnessExecutionStrategy,
    HarnessLoopDriverRef,
    compile_harness_attempt,
)
from .loop_driver import (
    DELIBERATE_THEN_ACT_LOOP_DRIVER,
    SEQUENTIAL_LOOP_DRIVER,
)
from .independent_result import (
    IndependentCompletionProposal,
    IndependentHarnessRunReceipt,
    IndependentRunRecorder,
    StoredIndependentRunResult,
)
from .strategy_selection import (
    HarnessAgentStrategySelection,
    HarnessPriorAttemptEvidence,
    HarnessStrategyEvidence,
    HarnessStrategySelectionContext,
    admit_harness_agent_strategy,
    build_harness_strategy_selection_context,
    compile_harness_selected_attempt,
    derive_harness_mandate_consumption,
)
from .ordivon.continuity_records import (
    HarnessDispatchFenceV2,
    HarnessProviderCallRecordV2,
    HarnessProviderCallRecordV3,
    HarnessProviderCallRecordV4,
)
from .ordivon.deepseek import (
    DEFAULT_DEEPSEEK_BASE_URL,
    DEFAULT_DEEPSEEK_SECRET_PATH,
    SUPPORTED_DEEPSEEK_MODELS,
    DeepSeekSettings,
    DeepSeekTurnAdapter,
)
from .ordivon.loop import (
    AgentLoopResult,
    CancellationToken,
    OrdivonAgentLoop,
    RunBudget,
    RunStopCode,
)
from .ordivon.model import (
    AgentRunConclusion,
    AgentToolCall,
    AgentToolDefinition,
    AgentTurnAdapter,
    AgentTurnAdapterError,
    AgentTurnRequest,
    AgentTurnResult,
    ScriptedTurnAdapter,
)
from .ordivon.run_store_port import (
    HarnessProviderCallClaimHeld,
    HarnessProviderCallRecoveryRequired,
    HarnessProviderCallRequestMismatch,
    HarnessRunContinuityStore,
    HarnessRunStoreBinding,
)
from .ordivon.sqlite_agent_bridge import (
    NO_TOOL_AGENT_GRANT,
    NO_TOOL_AGENT_GRANT_DIGEST,
    NO_TOOL_AGENT_SURFACE,
    NO_TOOL_AGENT_SURFACE_DIGEST,
    SQLiteHarnessAgentBridge,
)
from .ordivon.sqlite_run_store import SQLiteHarnessRunContinuityStore
from .ordivon.sqlite_runtime_bridge import (
    INDEPENDENT_SEARCH_TOOL_GRANT,
    INDEPENDENT_SEARCH_TOOL_GRANT_DIGEST,
    INDEPENDENT_SEARCH_TOOL_SURFACE,
    INDEPENDENT_SEARCH_TOOL_SURFACE_DIGEST,
    SEARCH_WORKSPACE_DEFINITION,
    SQLiteHarnessRuntimeBridge,
)
from .observation_tool_surface import (
    OBSERVATION_TOOL_DEFINITIONS,
    OBSERVATION_TOOL_SURFACE,
    OBSERVATION_TOOL_SURFACE_DIGEST,
    READ_WORKSPACE_DEFINITION,
    HarnessObservationAuthorityStatementProjection,
    HarnessObservationReadObject,
    HarnessObservationSourceAuthority,
    HarnessObservationToolGrant,
    build_observation_tool_surface,
)
from .recovery import NativeRunRecoveryAssessment
from .runtime_port import (
    HarnessRuntimeClient,
    HarnessRuntimeClientError,
    HarnessRuntimeErrorDetail,
    HarnessRuntimeToolRejected,
    find_runtime_jobs_by_client_request,
)
from .sqlite_store import (
    HarnessEventConflict,
    HarnessJournalCorruption,
    HarnessLeaseConflict,
    HarnessLeaseHeld,
    HarnessObjectCorrupt,
    HarnessObjectMissing,
    HarnessRevisionConflict,
    HarnessStoreError,
    HarnessTerminalConflict,
    SQLiteHarnessStore,
)
from .standalone import (
    StandaloneHarnessExecution,
    StandaloneHarnessRunner,
    StandaloneToolBridge,
)
from .store import (
    HARNESS_STORE_EVENT_KINDS,
    HarnessEventAdmission,
    HarnessEventWrite,
    HarnessRunEventRecord,
    HarnessRunLease,
    HarnessRunProjection,
    HarnessRunStatus,
    HarnessStore,
    StoredHarnessObject,
)
from .store_ops import (
    backup_harness_store,
    restore_harness_backup,
    verify_harness_backup,
)
from .working_view import (
    AgentWorkingSetTransitionProposal,
    HarnessWorkingSetPin,
    HarnessWorkingSetSpec,
    HarnessWorkingView,
    HarnessWorkingViewSource,
    compile_working_view,
)
from .version import package_version

__all__ = [
    "DEFAULT_DEEPSEEK_BASE_URL",
    "DEFAULT_DEEPSEEK_SECRET_PATH",
    "DELIBERATE_THEN_ACT_LOOP_DRIVER",
    "HARNESS_STORE_EVENT_KINDS",
    "INDEPENDENT_SEARCH_TOOL_GRANT",
    "INDEPENDENT_SEARCH_TOOL_GRANT_DIGEST",
    "INDEPENDENT_SEARCH_TOOL_SURFACE",
    "INDEPENDENT_SEARCH_TOOL_SURFACE_DIGEST",
    "NO_TOOL_AGENT_GRANT",
    "NO_TOOL_AGENT_GRANT_DIGEST",
    "NO_TOOL_AGENT_SURFACE",
    "NO_TOOL_AGENT_SURFACE_DIGEST",
    "OBSERVATION_TOOL_DEFINITIONS",
    "OBSERVATION_TOOL_SURFACE",
    "OBSERVATION_TOOL_SURFACE_DIGEST",
    "READ_WORKSPACE_DEFINITION",
    "SEARCH_WORKSPACE_DEFINITION",
    "SEQUENTIAL_LOOP_DRIVER",
    "SUPPORTED_DEEPSEEK_MODELS",
    "AgentLoopResult",
    "AgentRunConclusion",
    "AgentWorkingSetTransitionProposal",
    "AgentToolCall",
    "AgentToolDefinition",
    "AgentTurnAdapter",
    "AgentTurnAdapterError",
    "AgentTurnRequest",
    "AgentTurnResult",
    "CancellationToken",
    "CompiledHarnessAttempt",
    "DeepSeekSettings",
    "DeepSeekTurnAdapter",
    "HarnessArtifactReference",
    "HarnessBoundReference",
    "HarnessCorrelationContext",
    "HarnessDispatchFenceV2",
    "HarnessEventAdmission",
    "HarnessEventWrite",
    "HarnessEventConflict",
    "HarnessExecutionBinding",
    "HarnessExecutionMandate",
    "HarnessMandateConsumption",
    "HarnessExecutionProfile",
    "HarnessExecutionStrategy",
    "HarnessLoopDriverRef",
    "HarnessAgentStrategySelection",
    "HarnessPriorAttemptEvidence",
    "HarnessStrategyEvidence",
    "HarnessStrategySelectionContext",
    "HarnessJournalCorruption",
    "HarnessLeaseConflict",
    "HarnessLeaseHeld",
    "HarnessObjectCorrupt",
    "HarnessObjectMissing",
    "HarnessObservationAuthorityStatementProjection",
    "HarnessObservationReadObject",
    "HarnessObservationSourceAuthority",
    "HarnessObservationToolGrant",
    "HarnessPrivacyPolicy",
    "HarnessProviderCallClaimHeld",
    "HarnessProviderCallRecordV2",
    "HarnessProviderCallRecordV3",
    "HarnessProviderCallRecordV4",
    "HarnessProviderCallRecoveryRequired",
    "HarnessProviderCallRequestMismatch",
    "HarnessRevisionConflict",
    "HarnessRunContinuityStore",
    "HarnessRunContract",
    "STRUCTURED_COMPLETION_MODE",
    "HarnessRunEventRecord",
    "HarnessRunLease",
    "HarnessRunProjection",
    "HarnessRunStatus",
    "HarnessRunStoreBinding",
    "HarnessRuntimeClient",
    "HarnessRuntimeClientError",
    "HarnessRuntimeErrorDetail",
    "HarnessRuntimeReference",
    "HarnessRuntimeToolRejected",
    "HarnessStore",
    "HarnessStoreError",
    "HarnessTerminalConflict",
    "HarnessToolObservation",
    "HarnessWorkingSetPin",
    "HarnessWorkingSetSpec",
    "HarnessWorkingView",
    "HarnessWorkingViewSource",
    "IndependentCompletionProposal",
    "IndependentHarnessRunReceipt",
    "IndependentRunRecorder",
    "NativeRunRecoveryAssessment",
    "OperationalClaimEvidenceRole",
    "OperationalClaimRef",
    "OperationalClaimStandingView",
    "OrdivonAgentLoop",
    "RunBudget",
    "RunStopCode",
    "SQLiteHarnessAgentBridge",
    "SQLiteHarnessRunContinuityStore",
    "SQLiteHarnessRuntimeBridge",
    "SQLiteHarnessStore",
    "ScriptedTurnAdapter",
    "StandaloneHarnessExecution",
    "StandaloneHarnessRunner",
    "StandaloneToolBridge",
    "StoredHarnessObject",
    "StoredIndependentRunResult",
    "admit_harness_agent_strategy",
    "backup_harness_store",
    "build_observation_tool_surface",
    "build_harness_strategy_selection_context",
    "build_harness_workspace_exec_request_from_binding",
    "compile_harness_attempt",
    "compile_harness_selected_attempt",
    "compile_working_view",
    "derive_harness_mandate_consumption",
    "decode_structured_completion_result",
    "find_runtime_jobs_by_client_request",
    "package_version",
    "project_operational_claim_standing_view",
    "restore_harness_backup",
    "structured_completion_contract_digest",
    "structured_completion_result_schema",
    "verify_harness_backup",
]
