from __future__ import annotations

from ._host_compat.domain import EventKind

HARNESS_ASSIGNMENT_COMMITTED = EventKind("harness.assignment-committed")
HARNESS_RUN_RECOVERY_RECORDED = EventKind("harness.run-recovery-recorded")
HARNESS_RUN_ABANDONED = EventKind("harness.run-abandoned")
HARNESS_RUN_RECORDED = EventKind("harness.run-recorded")
HARNESS_PROVIDER_CALL_CLAIMED = EventKind("harness.provider-call-claimed")
HARNESS_PROVIDER_CALL_COMPLETED = EventKind("harness.provider-call-completed")
HARNESS_PROVIDER_CALL_DISPATCHING = EventKind("harness.provider-call-dispatching")
HARNESS_PROVIDER_CALL_FAILED = EventKind("harness.provider-call-failed")
HARNESS_PROVIDER_CALL_SUPERSEDED = EventKind("harness.provider-call-superseded")
HARNESS_PROVIDER_CALL_UNKNOWN = EventKind("harness.provider-call-unknown")
HARNESS_TOOL_STEP_PREPARED = EventKind("harness.tool-step-prepared")
HARNESS_TOOL_STEP_RECORDED = EventKind("harness.tool-step-recorded")
HARNESS_RUN_SNAPSHOT_RECORDED = EventKind("harness.run-snapshot-recorded")
COMPLETION_PROPOSED = EventKind("completion.proposed")
COMPLETION_DECIDED = EventKind("completion.decided")

HARNESS_EVENT_KINDS = frozenset(
    {
        HARNESS_ASSIGNMENT_COMMITTED,
        HARNESS_RUN_RECOVERY_RECORDED,
        HARNESS_RUN_ABANDONED,
        HARNESS_RUN_RECORDED,
        HARNESS_PROVIDER_CALL_CLAIMED,
        HARNESS_PROVIDER_CALL_COMPLETED,
        HARNESS_PROVIDER_CALL_DISPATCHING,
        HARNESS_PROVIDER_CALL_FAILED,
        HARNESS_PROVIDER_CALL_SUPERSEDED,
        HARNESS_PROVIDER_CALL_UNKNOWN,
        HARNESS_TOOL_STEP_PREPARED,
        HARNESS_TOOL_STEP_RECORDED,
        HARNESS_RUN_SNAPSHOT_RECORDED,
        COMPLETION_PROPOSED,
        COMPLETION_DECIDED,
    }
)

__all__ = [
    "COMPLETION_DECIDED",
    "COMPLETION_PROPOSED",
    "HARNESS_ASSIGNMENT_COMMITTED",
    "HARNESS_EVENT_KINDS",
    "HARNESS_RUN_ABANDONED",
    "HARNESS_RUN_RECORDED",
    "HARNESS_RUN_RECOVERY_RECORDED",
    "HARNESS_RUN_SNAPSHOT_RECORDED",
    "HARNESS_PROVIDER_CALL_CLAIMED",
    "HARNESS_PROVIDER_CALL_COMPLETED",
    "HARNESS_PROVIDER_CALL_DISPATCHING",
    "HARNESS_PROVIDER_CALL_FAILED",
    "HARNESS_PROVIDER_CALL_SUPERSEDED",
    "HARNESS_PROVIDER_CALL_UNKNOWN",
    "HARNESS_TOOL_STEP_PREPARED",
    "HARNESS_TOOL_STEP_RECORDED",
]
